import { Generated, Selectable, Insertable, Updateable, ColumnType } from 'kysely'

// --- users ---
export interface UsersTable {
  id: Generated<string>             // uuid, generated by Postgres
  display_name: string | null
  color_theme: Generated<string>    // default 'theme-dark'
  created_at: Generated<Date>
  updated_at: Generated<Date>
}

export type User = Selectable<UsersTable>
export type NewUser = Insertable<UsersTable>
export type UserUpdate = Updateable<UsersTable>

// --- notes ---
export interface NotesTable {
  id: Generated<string>             // uuid, generated by Postgres
  user_id: string
  title: string | null
  content: ColumnType<unknown, string | unknown, string | unknown>  // jsonb
  synthesis: string | null
  created_at: Generated<Date>
  updated_at: Generated<Date>
  synthesized_at: Date | null
  deleted_at: Date | null
}

export type Note = Selectable<NotesTable>
export type NewNote = Insertable<NotesTable>
export type NoteUpdate = Updateable<NotesTable>

// --- tags ---
export interface TagsTable {
  id: Generated<number>             // serial
  user_id: string
  name: string
  created_at: Generated<Date>
}

export type Tag = Selectable<TagsTable>
export type NewTag = Insertable<TagsTable>
export type TagUpdate = Updateable<TagsTable>

// --- note_tags ---
export interface NoteTagsTable {
  note_id: string
  tag_id: number
}

export type NoteTag = Selectable<NoteTagsTable>
export type NewNoteTag = Insertable<NoteTagsTable>

// --- database ---
export interface Database {
  users: UsersTable
  notes: NotesTable
  tags: TagsTable
  note_tags: NoteTagsTable
}
